### ISSUE TITLE
ci: safari and edge tests on macOS can sporadically fail

### ISSUE THREAD

**Issue by lread** [clj-commons/etaoin#464]
## Currently 

It is not unusual for safari tests to fail on GitHub Actions.
A re-run of any failed jobs usually succeeds.
I do not see these failures when running these tests locally on my macOS dev box.

## Impact

It is a bit annoying to have to rerun these sporadic failed jobs.

## Typical Symptom

The typical symptom is an `:etaoin/timeout` exception, example:
```Clojure
=== test-title [jvm][safari]
Error: Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:type :etaoin/timeout, :message nil, :timeout 7, :interval 0.33, :times 22, :predicate #object[etaoin.api$wait_running$fn__7555 0x7db72209 "etaoin.api$wait_running$fn__7555@7db72209"]} {:type :etaoin/timeout, :message nil, :timeout 7, :interval 0.33, :times 22, :predicate #object[etaoin.api$wait_running$fn__7555 0x7db72209 "etaoin.api$wait_running$fn__7555@7db72209"]}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at etaoin.api$wait_predicate.invokeStatic(api.clj:2473)
	at etaoin.api$wait_predicate.invoke(api.clj:2451)
	at etaoin.api$wait_running.invokeStatic(api.clj:2605)
	at etaoin.api$wait_running.doInvoke(api.clj:2594)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at etaoin.api$_connect_driver.invokeStatic(api.clj:3548)
	at etaoin.api$_connect_driver.doInvoke(api.clj:3484)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at etaoin.api$boot_driver.invokeStatic(api.clj:3609)
	at etaoin.api$boot_driver.invoke(api.clj:3593)
	at etaoin.api_test$fixture_browsers$fn__8111.invoke(api_test.clj:56)
	at etaoin.api_test$fixture_browsers.invokeStatic(api_test.clj:56)
	at etaoin.api_test$fixture_browsers.invoke(api_test.clj:53)
	at clojure.test$compose_fixtures$fn__9203$fn__9204.invoke(test.clj:693)
	at clojure.test$default_fixture.invokeStatic(test.clj:686)
	at clojure.test$default_fixture.invoke(test.clj:682)
	at clojure.test$compose_fixtures$fn__9203.invoke(test.clj:693)
	at clojure.test$test_vars$fn__9235.invoke(test.clj:734)
	at etaoin.api_test$report_browsers.invokeStatic(api_test.clj:70)
	at etaoin.api_test$report_browsers.invoke(api_test.clj:68)
	at clojure.test$compose_fixtures$fn__9203$fn__9204.invoke(test.clj:693)
	at clojure.test$default_fixture.invokeStatic(test.clj:686)
	at clojure.test$default_fixture.invoke(test.clj:682)
	at clojure.test$compose_fixtures$fn__9203.invoke(test.clj:693)
	at clojure.test$test_vars.invokeStatic(test.clj:730)
	at clojure.test$test_all_vars.invokeStatic(test.clj:736)
	at clojure.test$test_ns.invokeStatic(test.clj:757)
	at clojure.test$test_ns.invoke(test.clj:742)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1785)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.test$run_tests.invokeStatic(test.clj:767)
	at clojure.test$run_tests.doInvoke(test.clj:767)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at cognitect.test_runner$test.invokeStatic(test_runner.clj:74)
	at cognitect.test_runner$test.invoke(test_runner.clj:62)
	at cognitect.test_runner$_main.invokeStatic(test_runner.clj:127)
	at cognitect.test_runner$_main.doInvoke(test_runner.clj:115)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```

## Thoughts
I do notice on my local macOS dev box that the safaridriver can take a few seconds to start sometimes.

Perhaps simply increasing the timeout for safari from 7 seconds to something a little larger will do the trick.

When Etaoin is the one who has launched the WebDriver process it could also check if the process actually still seems to be running (I don't think we currently do this?).

**Comment by lread** [comment]
Have been playing around in a branch on my fork.

Have discovered that sometimes the safaridriver will exit with `1`. 

A dump from safaridriver stderr when this happens (stdout was empty):
```
-[WebDriver err log dump]-
Unable to start the server: Operation not permitted
```

The sporadic nature of the failure condition is odd to me.

**Comment by lread** [comment]
More hacking in my branch tells me that when safaridriver exits unexpectedly with a 1 on launch, a subsequent launch can succeed.

Coincidentally one attempt to launch safaridriver from my REPL `(def d (e/safari))` on my macOS dev box failed for me with an exit code of 1. First time I've noticed this. A subsequent retry worked fine.

Soo... It might be reasonable to retry a WebDriver launch if it exits unexpectedly on launch.

**Comment by lread** [comment]
From my hack-branch: Retrying a failed safaridriver launch seems to consistently work.

**Comment by lread** [comment]
> Perhaps simply increasing the timeout for safari from 7 seconds to something a little larger will do the trick.

Preliminary findings suggest that this is not necessary.
The launch retry seems to do the trick.

**Comment by lread** [comment]
Things should be much improved by #468
Will re-open if necessary.
